baseURL: 'https://dflib.org/'

# Override default directory structure of Hugo to blend with the Maven build
publishDir: ../../../../docs
# Hugo generated resources (like processed images), even if there are non, this directory would be created
resourceDir: ../../../target/hugo/resources
assetDir: src

title: DFLib Java DataFrame Library | Official Site

defaultContentLanguage: en
languageName: English
languageCode: en-US

params:
  description: 'DFLib is an open source lightweight Java in-memory DataFrame with unique data manipulation API to process data incrementally in a highly-composable manner. DFLib supports loading and saving to CSV, Excel, RDBMS, Avro, Parquet, and JSON formats, and works with a variety of data sources'

disableKinds:
  - RSS
  - taxonomy
  - term

disableHugoGeneratorInject: true

enableRobotsTXT: true

outputs:
  - HTML

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    guessSyntax: false