baseURL: 'https://dflib.org/'

# Override default directory structure of Hugo to blend with the Maven build
publishDir: ../../../../docs
# Hugo generated resources (like processed images), even if there are non, this directory would be created
resourceDir: ../../../target/hugo/resources
assetDir: src
module:
  mounts:
    - source: static
      target: static
    - source: ../../../target/hugo/docs
      target: static # TODO: once docs are using proper templating, this should be changed to content

title: DFLib Java DataFrame Library | Official Site

defaultContentLanguage: en
languageName: English
languageCode: en-US

params:
  description: "DFLib is a lightweight, pure Java implementation of a DataFrame data structure. It provides data manipulation capabilities similar to SQL: filtering, joins, unions, and more. DFLib supports CSV, Excel, RDBMS, Avro, Parquet, JSON formats"
  keywords: "DFLib, DataFrame, Java, ETL, data analysis, data transformation, data visualization, Jupyter, Jupyter notebook, Jupyter kernel"

disableKinds:
  - RSS
  - taxonomy
  - term

enableRobotsTXT: true

outputs:
  - HTML

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    guessSyntax: false